import json
import pickle
import requests
import numpy as np

FEATURES = ["valence", "energy", "danceability", "tempo",
            "acousticness", "speechiness", "instrumentalness",
            "loudness"]

# Target audio features per mood — these get passed to Spotify's
# recommendations endpoint as target values
MOOD_TARGETS = {
    "epic": {
        "target_valence":      0.34,
        "target_energy":       0.75,
        "target_danceability": 0.58,
        "target_acousticness": 0.11,
        "target_instrumentalness": 0.78,
    },
    "energized": {
        "target_valence":      0.41,
        "target_energy":       0.82,
        "target_danceability": 0.49,
        "target_acousticness": 0.09,
        "target_instrumentalness": 0.03,
    },
    "melancholic": {
        "target_valence":      0.37,
        "target_energy":       0.37,
        "target_danceability": 0.51,
        "target_acousticness": 0.69,
        "target_instrumentalness": 0.03,
    },
    "happy": {
        "target_valence":      0.69,
        "target_energy":       0.70,
        "target_danceability": 0.70,
        "target_acousticness": 0.26,
        "target_instrumentalness": 0.02,
    },
    "chill": {
        "target_valence":      0.19,
        "target_energy":       0.18,
        "target_danceability": 0.35,
        "target_acousticness": 0.86,
        "target_instrumentalness": 0.81,
    },
}


def get_headers(access_token):
    return {"Authorization": f"Bearer {access_token}"}


# ── Get seed tracks for a mood from labeled library ───────────────────
def get_seed_tracks(mood, n=5):
    """
    Pick the top n highest-confidence tracks for the mood
    from the labeled library — these seed Spotify's recommendations.
    Spotify allows max 5 seeds total.
    """
    with open("labeled_library.json") as f:
        tracks = json.load(f)

    mood_tracks = [t for t in tracks if t["mood"] == mood]
    mood_tracks.sort(key=lambda x: x["confidence"], reverse=True)
    seeds = mood_tracks[:n]

    print(f"Seeds for '{mood}':")
    for s in seeds:
        print(f"  {s['confidence']:.2f}  {s['name']} — {s['artist']}")

    return [s["id"] for s in seeds]


# ── Get recommendations from Spotify ─────────────────────────────────
def get_recommendations(access_token, mood, n_tracks=30):
    """
    Call Spotify's recommendations endpoint with:
    - seed tracks from our labeled library
    - target audio features derived from the mood's cluster centroid
    Returns a list of recommended tracks.
    """
    seed_ids = get_seed_tracks(mood)

    if not seed_ids:
        print(f"No seed tracks found for mood '{mood}'")
        return []

    params = {
        "seed_tracks": ",".join(seed_ids),
        "limit":       n_tracks,
        **MOOD_TARGETS[mood],  # unpack target audio features
    }

    response = requests.get(
        "https://api.spotify.com/v1/recommendations",
        headers=get_headers(access_token),
        params=params,
    )
    data = response.json()

    if "error" in data:
        print(f"Spotify error: {data['error']}")
        return []

    tracks = []
    for item in data.get("tracks", []):
        tracks.append({
            "id":     item["id"],
            "name":   item["name"],
            "artist": item["artists"][0]["name"],
            "uri":    item["uri"],
        })

    print(f"\nGot {len(tracks)} recommendations for '{mood}'")
    return tracks


# ── Create playlist on Spotify ────────────────────────────────────────
def create_playlist(access_token, mood, tracks):
    """
    Create a new playlist in the user's Spotify account
    and add the recommended tracks to it.
    """
    # Get the user's Spotify ID first
    user_response = requests.get(
        "https://api.spotify.com/v1/me",
        headers=get_headers(access_token),
    )
    user_id = user_response.json()["id"]

    # Create the playlist
    playlist_response = requests.post(
        f"https://api.spotify.com/v1/users/{user_id}/playlists",
        headers={**get_headers(access_token), "Content-Type": "application/json"},
        json={
            "name":        f"{mood.capitalize()} Mood 🎵",
            "description": f"Generated by your mood playlist app — {mood} vibes",
            "public":      False,
        },
    )
    playlist = playlist_response.json()
    playlist_id = playlist["id"]
    print(f"\nCreated playlist: {playlist['name']} (id: {playlist_id})")

    # Add tracks to the playlist
    uris = [t["uri"] for t in tracks]
    requests.post(
        f"https://api.spotify.com/v1/playlists/{playlist_id}/tracks",
        headers={**get_headers(access_token), "Content-Type": "application/json"},
        json={"uris": uris},
    )

    print(f"Added {len(tracks)} tracks to playlist")
    print(f"Open in Spotify: spotify:playlist:{playlist_id}")
    return playlist_id


# ── Main: generate a playlist for a mood ─────────────────────────────
def generate_playlist(access_token, mood):
    if mood not in MOOD_TARGETS:
        print(f"Unknown mood. Choose from: {list(MOOD_TARGETS.keys())}")
        return

    print(f"\n{'='*55}")
    print(f"Generating {mood.upper()} playlist...")
    print(f"{'='*55}")

    tracks    = get_recommendations(access_token, mood)
    if not tracks:
        return

    print("\nRecommended tracks:")
    for i, t in enumerate(tracks, 1):
        print(f"  {i:>2}. {t['name']} — {t['artist']}")

    playlist_id = create_playlist(access_token, mood, tracks)
    return playlist_id